### ISSUE TITLE
Decoding exception when using load_image_from_dsc on < iOS 16

### ISSUE THREAD

**Issue by glen-mac** [0cyn/ktool#45]
Don't have trace on-hand atm, but using ktool as a lib I'm getting:

> utf-8 can't decode byte 0xc0 in position 2: invalid start byte

from read_node in ktool/loader.py in the image.get_cstr_at(cursor) call.

Let me know if you need the full trace

**Comment by 0cyn** [comment]
I've made the decision to drop dsc support as it was a nightmare to work on and maintain within the scope of this project. See issue #54 

For future stuff regarding development efforts, https://github.com/arandomdev/dyldextractor should be used.
